// flow-typed signature: c60aa52c89fac8cf5cd9692988b1f414
// flow-typed version: <<STUB>>/awesome-phonenumber_v^2.5.0/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'awesome-phonenumber'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'awesome-phonenumber' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'awesome-phonenumber/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'awesome-phonenumber/index' {
  declare module.exports: $Exports<'awesome-phonenumber'>;
}
declare module 'awesome-phonenumber/index.js' {
  declare module.exports: $Exports<'awesome-phonenumber'>;
}
declare module 'awesome-phonenumber/lib/index.js' {
  declare module.exports: $Exports<'awesome-phonenumber/lib/index'>;
}
