// flow-typed signature: 0572fba1b35a31ea0ba3dc84680631d7
// flow-typed version: <<STUB>>/material-ui-snackbar-provider_v^1.1.0/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'material-ui-snackbar-provider'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'material-ui-snackbar-provider' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'material-ui-snackbar-provider/lib/index' {
  declare module.exports: any;
}

declare module 'material-ui-snackbar-provider/lib/SnackbarProvider' {
  declare module.exports: any;
}

declare module 'material-ui-snackbar-provider/lib/withSnackbar' {
  declare module.exports: any;
}

// Filename aliases
declare module 'material-ui-snackbar-provider/lib/index.js' {
  declare module.exports: $Exports<'material-ui-snackbar-provider/lib/index'>;
}
declare module 'material-ui-snackbar-provider/lib/SnackbarProvider.js' {
  declare module.exports: $Exports<'material-ui-snackbar-provider/lib/SnackbarProvider'>;
}
declare module 'material-ui-snackbar-provider/lib/withSnackbar.js' {
  declare module.exports: $Exports<'material-ui-snackbar-provider/lib/withSnackbar'>;
}
