// flow-typed signature: d8430e4770e2de7c9a395d47ae918cf8
// flow-typed version: <<STUB>>/mui-places-autocomplete_v^2.0.0/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mui-places-autocomplete'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mui-places-autocomplete' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mui-places-autocomplete/demo/Demo' {
  declare module.exports: any;
}

declare module 'mui-places-autocomplete/demo/DemoBasic' {
  declare module.exports: any;
}

declare module 'mui-places-autocomplete/demo/DemoControlledInput' {
  declare module.exports: any;
}

declare module 'mui-places-autocomplete/demo/DemoGeocodeLatLong' {
  declare module.exports: any;
}

declare module 'mui-places-autocomplete/demo/index' {
  declare module.exports: any;
}

declare module 'mui-places-autocomplete/demo/rootReducer' {
  declare module.exports: any;
}

declare module 'mui-places-autocomplete/demo/webpack.config' {
  declare module.exports: any;
}

declare module 'mui-places-autocomplete/dist/index' {
  declare module.exports: any;
}

declare module 'mui-places-autocomplete/src/geocode' {
  declare module.exports: any;
}

declare module 'mui-places-autocomplete/src/index' {
  declare module.exports: any;
}

declare module 'mui-places-autocomplete/src/MUIPlacesAutocomplete' {
  declare module.exports: any;
}

declare module 'mui-places-autocomplete/test/api-key' {
  declare module.exports: any;
}

declare module 'mui-places-autocomplete/test/setup-dom' {
  declare module.exports: any;
}

declare module 'mui-places-autocomplete/test/test' {
  declare module.exports: any;
}

declare module 'mui-places-autocomplete/test/testGeocode' {
  declare module.exports: any;
}

declare module 'mui-places-autocomplete/test/testHelper' {
  declare module.exports: any;
}

declare module 'mui-places-autocomplete/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mui-places-autocomplete/demo/Demo.jsx' {
  declare module.exports: $Exports<'mui-places-autocomplete/demo/Demo'>;
}
declare module 'mui-places-autocomplete/demo/DemoBasic.jsx' {
  declare module.exports: $Exports<'mui-places-autocomplete/demo/DemoBasic'>;
}
declare module 'mui-places-autocomplete/demo/DemoControlledInput.jsx' {
  declare module.exports: $Exports<'mui-places-autocomplete/demo/DemoControlledInput'>;
}
declare module 'mui-places-autocomplete/demo/DemoGeocodeLatLong.jsx' {
  declare module.exports: $Exports<'mui-places-autocomplete/demo/DemoGeocodeLatLong'>;
}
declare module 'mui-places-autocomplete/demo/index.jsx' {
  declare module.exports: $Exports<'mui-places-autocomplete/demo/index'>;
}
declare module 'mui-places-autocomplete/demo/rootReducer.js' {
  declare module.exports: $Exports<'mui-places-autocomplete/demo/rootReducer'>;
}
declare module 'mui-places-autocomplete/demo/webpack.config.js' {
  declare module.exports: $Exports<'mui-places-autocomplete/demo/webpack.config'>;
}
declare module 'mui-places-autocomplete/dist/index.js' {
  declare module.exports: $Exports<'mui-places-autocomplete/dist/index'>;
}
declare module 'mui-places-autocomplete/src/geocode.js' {
  declare module.exports: $Exports<'mui-places-autocomplete/src/geocode'>;
}
declare module 'mui-places-autocomplete/src/index.js' {
  declare module.exports: $Exports<'mui-places-autocomplete/src/index'>;
}
declare module 'mui-places-autocomplete/src/MUIPlacesAutocomplete.jsx' {
  declare module.exports: $Exports<'mui-places-autocomplete/src/MUIPlacesAutocomplete'>;
}
declare module 'mui-places-autocomplete/test/api-key.js' {
  declare module.exports: $Exports<'mui-places-autocomplete/test/api-key'>;
}
declare module 'mui-places-autocomplete/test/setup-dom.js' {
  declare module.exports: $Exports<'mui-places-autocomplete/test/setup-dom'>;
}
declare module 'mui-places-autocomplete/test/test.jsx' {
  declare module.exports: $Exports<'mui-places-autocomplete/test/test'>;
}
declare module 'mui-places-autocomplete/test/testGeocode.js' {
  declare module.exports: $Exports<'mui-places-autocomplete/test/testGeocode'>;
}
declare module 'mui-places-autocomplete/test/testHelper.js' {
  declare module.exports: $Exports<'mui-places-autocomplete/test/testHelper'>;
}
declare module 'mui-places-autocomplete/webpack.config.js' {
  declare module.exports: $Exports<'mui-places-autocomplete/webpack.config'>;
}
