// flow-typed signature: f8ca048b850e47a21ed76ac7cd508fc8
// flow-typed version: <<STUB>>/react-app-env_v^1.2.3/flow_v0.92.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-app-env'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-app-env' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-app-env/__tests__/index' {
  declare module.exports: any;
}

declare module 'react-app-env/lib/index' {
  declare module.exports: any;
}

declare module 'react-app-env/lib/parse-env-file' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-app-env/__tests__/index.js' {
  declare module.exports: $Exports<'react-app-env/__tests__/index'>;
}
declare module 'react-app-env/lib/index.js' {
  declare module.exports: $Exports<'react-app-env/lib/index'>;
}
declare module 'react-app-env/lib/parse-env-file.js' {
  declare module.exports: $Exports<'react-app-env/lib/parse-env-file'>;
}
