// flow-typed signature: 6a0ffff88fa3635cb73802c8f436760d
// flow-typed version: <<STUB>>/react-rating_v1.7.2/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-rating'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-rating' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-rating/lib/react-rating.cjs' {
  declare module.exports: any;
}

declare module 'react-rating/lib/react-rating.esm' {
  declare module.exports: any;
}

declare module 'react-rating/lib/react-rating.umd' {
  declare module.exports: any;
}

declare module 'react-rating/lib/react-rating.umd.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-rating/lib/react-rating.cjs.js' {
  declare module.exports: $Exports<'react-rating/lib/react-rating.cjs'>;
}
declare module 'react-rating/lib/react-rating.esm.js' {
  declare module.exports: $Exports<'react-rating/lib/react-rating.esm'>;
}
declare module 'react-rating/lib/react-rating.umd.js' {
  declare module.exports: $Exports<'react-rating/lib/react-rating.umd'>;
}
declare module 'react-rating/lib/react-rating.umd.min.js' {
  declare module.exports: $Exports<'react-rating/lib/react-rating.umd.min'>;
}
