// flow-typed signature: 9e208097a95a6580b34320695967b4b9
// flow-typed version: <<STUB>>/semantic-ui-calendar-react_v0.15.0/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'semantic-ui-calendar-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'semantic-ui-calendar-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'semantic-ui-calendar-react/dist/amd/index' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/amd/inputs/BaseInput' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/amd/inputs/DateInput' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/amd/inputs/DatesRangeInput' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/amd/inputs/DateTimeInput' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/amd/inputs/index' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/amd/inputs/MonthInput' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/amd/inputs/MonthRangeInput' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/amd/inputs/parse' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/amd/inputs/shared' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/amd/inputs/TimeInput' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/amd/inputs/YearInput' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/amd/lib/checkIE' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/amd/lib/checkMobile' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/amd/lib/CustomPropTypes' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/amd/lib/findHTMLElement' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/amd/lib/index' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/amd/lib/tick' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/amd/pickers/BasePicker' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/amd/pickers/dayPicker/DatesRangePicker' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/amd/pickers/dayPicker/DayPicker' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/amd/pickers/dayPicker/sharedFunctions' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/amd/pickers/monthPicker/const' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/amd/pickers/monthPicker/MonthPicker' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/amd/pickers/monthPicker/MonthRangePicker' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/amd/pickers/monthPicker/sharedFunctions' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/amd/pickers/timePicker/HourPicker' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/amd/pickers/timePicker/MinutePicker' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/amd/pickers/timePicker/sharedFunctions' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/amd/pickers/YearPicker' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/amd/views/BaseCalendarView' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/amd/views/Calendar' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/amd/views/CalendarBody/Body' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/amd/views/CalendarBody/Cell' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/amd/views/CalendarBody/index' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/amd/views/CalendarHeader/Header' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/amd/views/CalendarHeader/HeaderRange' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/amd/views/CalendarHeader/HeaderWeeks' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/amd/views/CalendarHeader/index' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/amd/views/DatesRangeView' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/amd/views/DayView' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/amd/views/HourView' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/amd/views/InputView' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/amd/views/MinuteView' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/amd/views/MonthRangeView' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/amd/views/MonthView' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/amd/views/YearView' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/commonjs/index' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/commonjs/inputs/BaseInput' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/commonjs/inputs/DateInput' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/commonjs/inputs/DatesRangeInput' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/commonjs/inputs/DateTimeInput' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/commonjs/inputs/index' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/commonjs/inputs/MonthInput' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/commonjs/inputs/MonthRangeInput' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/commonjs/inputs/parse' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/commonjs/inputs/shared' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/commonjs/inputs/TimeInput' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/commonjs/inputs/YearInput' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/commonjs/lib/checkIE' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/commonjs/lib/checkMobile' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/commonjs/lib/CustomPropTypes' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/commonjs/lib/findHTMLElement' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/commonjs/lib/index' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/commonjs/lib/tick' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/commonjs/pickers/BasePicker' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/commonjs/pickers/dayPicker/DatesRangePicker' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/commonjs/pickers/dayPicker/DayPicker' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/commonjs/pickers/dayPicker/sharedFunctions' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/commonjs/pickers/monthPicker/const' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/commonjs/pickers/monthPicker/MonthPicker' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/commonjs/pickers/monthPicker/MonthRangePicker' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/commonjs/pickers/monthPicker/sharedFunctions' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/commonjs/pickers/timePicker/HourPicker' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/commonjs/pickers/timePicker/MinutePicker' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/commonjs/pickers/timePicker/sharedFunctions' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/commonjs/pickers/YearPicker' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/commonjs/views/BaseCalendarView' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/commonjs/views/Calendar' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/commonjs/views/CalendarBody/Body' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/commonjs/views/CalendarBody/Cell' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/commonjs/views/CalendarBody/index' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/commonjs/views/CalendarHeader/Header' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/commonjs/views/CalendarHeader/HeaderRange' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/commonjs/views/CalendarHeader/HeaderWeeks' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/commonjs/views/CalendarHeader/index' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/commonjs/views/DatesRangeView' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/commonjs/views/DayView' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/commonjs/views/HourView' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/commonjs/views/InputView' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/commonjs/views/MinuteView' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/commonjs/views/MonthRangeView' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/commonjs/views/MonthView' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/commonjs/views/YearView' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/es6/index' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/es6/inputs/BaseInput' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/es6/inputs/DateInput' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/es6/inputs/DatesRangeInput' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/es6/inputs/DateTimeInput' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/es6/inputs/index' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/es6/inputs/MonthInput' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/es6/inputs/MonthRangeInput' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/es6/inputs/parse' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/es6/inputs/shared' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/es6/inputs/TimeInput' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/es6/inputs/YearInput' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/es6/lib/checkIE' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/es6/lib/checkMobile' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/es6/lib/CustomPropTypes' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/es6/lib/findHTMLElement' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/es6/lib/index' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/es6/lib/tick' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/es6/pickers/BasePicker' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/es6/pickers/dayPicker/DatesRangePicker' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/es6/pickers/dayPicker/DayPicker' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/es6/pickers/dayPicker/sharedFunctions' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/es6/pickers/monthPicker/const' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/es6/pickers/monthPicker/MonthPicker' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/es6/pickers/monthPicker/MonthRangePicker' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/es6/pickers/monthPicker/sharedFunctions' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/es6/pickers/timePicker/HourPicker' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/es6/pickers/timePicker/MinutePicker' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/es6/pickers/timePicker/sharedFunctions' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/es6/pickers/YearPicker' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/es6/views/BaseCalendarView' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/es6/views/Calendar' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/es6/views/CalendarBody/Body' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/es6/views/CalendarBody/Cell' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/es6/views/CalendarBody/index' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/es6/views/CalendarHeader/Header' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/es6/views/CalendarHeader/HeaderRange' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/es6/views/CalendarHeader/HeaderWeeks' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/es6/views/CalendarHeader/index' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/es6/views/DatesRangeView' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/es6/views/DayView' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/es6/views/HourView' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/es6/views/InputView' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/es6/views/MinuteView' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/es6/views/MonthRangeView' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/es6/views/MonthView' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/es6/views/YearView' {
  declare module.exports: any;
}

declare module 'semantic-ui-calendar-react/dist/umd/semantic-ui-calendar-react' {
  declare module.exports: any;
}

// Filename aliases
declare module 'semantic-ui-calendar-react/dist/amd/index.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/amd/index'>;
}
declare module 'semantic-ui-calendar-react/dist/amd/inputs/BaseInput.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/amd/inputs/BaseInput'>;
}
declare module 'semantic-ui-calendar-react/dist/amd/inputs/DateInput.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/amd/inputs/DateInput'>;
}
declare module 'semantic-ui-calendar-react/dist/amd/inputs/DatesRangeInput.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/amd/inputs/DatesRangeInput'>;
}
declare module 'semantic-ui-calendar-react/dist/amd/inputs/DateTimeInput.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/amd/inputs/DateTimeInput'>;
}
declare module 'semantic-ui-calendar-react/dist/amd/inputs/index.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/amd/inputs/index'>;
}
declare module 'semantic-ui-calendar-react/dist/amd/inputs/MonthInput.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/amd/inputs/MonthInput'>;
}
declare module 'semantic-ui-calendar-react/dist/amd/inputs/MonthRangeInput.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/amd/inputs/MonthRangeInput'>;
}
declare module 'semantic-ui-calendar-react/dist/amd/inputs/parse.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/amd/inputs/parse'>;
}
declare module 'semantic-ui-calendar-react/dist/amd/inputs/shared.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/amd/inputs/shared'>;
}
declare module 'semantic-ui-calendar-react/dist/amd/inputs/TimeInput.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/amd/inputs/TimeInput'>;
}
declare module 'semantic-ui-calendar-react/dist/amd/inputs/YearInput.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/amd/inputs/YearInput'>;
}
declare module 'semantic-ui-calendar-react/dist/amd/lib/checkIE.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/amd/lib/checkIE'>;
}
declare module 'semantic-ui-calendar-react/dist/amd/lib/checkMobile.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/amd/lib/checkMobile'>;
}
declare module 'semantic-ui-calendar-react/dist/amd/lib/CustomPropTypes.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/amd/lib/CustomPropTypes'>;
}
declare module 'semantic-ui-calendar-react/dist/amd/lib/findHTMLElement.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/amd/lib/findHTMLElement'>;
}
declare module 'semantic-ui-calendar-react/dist/amd/lib/index.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/amd/lib/index'>;
}
declare module 'semantic-ui-calendar-react/dist/amd/lib/tick.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/amd/lib/tick'>;
}
declare module 'semantic-ui-calendar-react/dist/amd/pickers/BasePicker.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/amd/pickers/BasePicker'>;
}
declare module 'semantic-ui-calendar-react/dist/amd/pickers/dayPicker/DatesRangePicker.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/amd/pickers/dayPicker/DatesRangePicker'>;
}
declare module 'semantic-ui-calendar-react/dist/amd/pickers/dayPicker/DayPicker.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/amd/pickers/dayPicker/DayPicker'>;
}
declare module 'semantic-ui-calendar-react/dist/amd/pickers/dayPicker/sharedFunctions.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/amd/pickers/dayPicker/sharedFunctions'>;
}
declare module 'semantic-ui-calendar-react/dist/amd/pickers/monthPicker/const.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/amd/pickers/monthPicker/const'>;
}
declare module 'semantic-ui-calendar-react/dist/amd/pickers/monthPicker/MonthPicker.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/amd/pickers/monthPicker/MonthPicker'>;
}
declare module 'semantic-ui-calendar-react/dist/amd/pickers/monthPicker/MonthRangePicker.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/amd/pickers/monthPicker/MonthRangePicker'>;
}
declare module 'semantic-ui-calendar-react/dist/amd/pickers/monthPicker/sharedFunctions.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/amd/pickers/monthPicker/sharedFunctions'>;
}
declare module 'semantic-ui-calendar-react/dist/amd/pickers/timePicker/HourPicker.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/amd/pickers/timePicker/HourPicker'>;
}
declare module 'semantic-ui-calendar-react/dist/amd/pickers/timePicker/MinutePicker.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/amd/pickers/timePicker/MinutePicker'>;
}
declare module 'semantic-ui-calendar-react/dist/amd/pickers/timePicker/sharedFunctions.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/amd/pickers/timePicker/sharedFunctions'>;
}
declare module 'semantic-ui-calendar-react/dist/amd/pickers/YearPicker.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/amd/pickers/YearPicker'>;
}
declare module 'semantic-ui-calendar-react/dist/amd/views/BaseCalendarView.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/amd/views/BaseCalendarView'>;
}
declare module 'semantic-ui-calendar-react/dist/amd/views/Calendar.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/amd/views/Calendar'>;
}
declare module 'semantic-ui-calendar-react/dist/amd/views/CalendarBody/Body.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/amd/views/CalendarBody/Body'>;
}
declare module 'semantic-ui-calendar-react/dist/amd/views/CalendarBody/Cell.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/amd/views/CalendarBody/Cell'>;
}
declare module 'semantic-ui-calendar-react/dist/amd/views/CalendarBody/index.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/amd/views/CalendarBody/index'>;
}
declare module 'semantic-ui-calendar-react/dist/amd/views/CalendarHeader/Header.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/amd/views/CalendarHeader/Header'>;
}
declare module 'semantic-ui-calendar-react/dist/amd/views/CalendarHeader/HeaderRange.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/amd/views/CalendarHeader/HeaderRange'>;
}
declare module 'semantic-ui-calendar-react/dist/amd/views/CalendarHeader/HeaderWeeks.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/amd/views/CalendarHeader/HeaderWeeks'>;
}
declare module 'semantic-ui-calendar-react/dist/amd/views/CalendarHeader/index.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/amd/views/CalendarHeader/index'>;
}
declare module 'semantic-ui-calendar-react/dist/amd/views/DatesRangeView.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/amd/views/DatesRangeView'>;
}
declare module 'semantic-ui-calendar-react/dist/amd/views/DayView.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/amd/views/DayView'>;
}
declare module 'semantic-ui-calendar-react/dist/amd/views/HourView.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/amd/views/HourView'>;
}
declare module 'semantic-ui-calendar-react/dist/amd/views/InputView.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/amd/views/InputView'>;
}
declare module 'semantic-ui-calendar-react/dist/amd/views/MinuteView.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/amd/views/MinuteView'>;
}
declare module 'semantic-ui-calendar-react/dist/amd/views/MonthRangeView.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/amd/views/MonthRangeView'>;
}
declare module 'semantic-ui-calendar-react/dist/amd/views/MonthView.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/amd/views/MonthView'>;
}
declare module 'semantic-ui-calendar-react/dist/amd/views/YearView.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/amd/views/YearView'>;
}
declare module 'semantic-ui-calendar-react/dist/commonjs/index.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/commonjs/index'>;
}
declare module 'semantic-ui-calendar-react/dist/commonjs/inputs/BaseInput.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/commonjs/inputs/BaseInput'>;
}
declare module 'semantic-ui-calendar-react/dist/commonjs/inputs/DateInput.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/commonjs/inputs/DateInput'>;
}
declare module 'semantic-ui-calendar-react/dist/commonjs/inputs/DatesRangeInput.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/commonjs/inputs/DatesRangeInput'>;
}
declare module 'semantic-ui-calendar-react/dist/commonjs/inputs/DateTimeInput.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/commonjs/inputs/DateTimeInput'>;
}
declare module 'semantic-ui-calendar-react/dist/commonjs/inputs/index.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/commonjs/inputs/index'>;
}
declare module 'semantic-ui-calendar-react/dist/commonjs/inputs/MonthInput.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/commonjs/inputs/MonthInput'>;
}
declare module 'semantic-ui-calendar-react/dist/commonjs/inputs/MonthRangeInput.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/commonjs/inputs/MonthRangeInput'>;
}
declare module 'semantic-ui-calendar-react/dist/commonjs/inputs/parse.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/commonjs/inputs/parse'>;
}
declare module 'semantic-ui-calendar-react/dist/commonjs/inputs/shared.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/commonjs/inputs/shared'>;
}
declare module 'semantic-ui-calendar-react/dist/commonjs/inputs/TimeInput.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/commonjs/inputs/TimeInput'>;
}
declare module 'semantic-ui-calendar-react/dist/commonjs/inputs/YearInput.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/commonjs/inputs/YearInput'>;
}
declare module 'semantic-ui-calendar-react/dist/commonjs/lib/checkIE.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/commonjs/lib/checkIE'>;
}
declare module 'semantic-ui-calendar-react/dist/commonjs/lib/checkMobile.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/commonjs/lib/checkMobile'>;
}
declare module 'semantic-ui-calendar-react/dist/commonjs/lib/CustomPropTypes.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/commonjs/lib/CustomPropTypes'>;
}
declare module 'semantic-ui-calendar-react/dist/commonjs/lib/findHTMLElement.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/commonjs/lib/findHTMLElement'>;
}
declare module 'semantic-ui-calendar-react/dist/commonjs/lib/index.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/commonjs/lib/index'>;
}
declare module 'semantic-ui-calendar-react/dist/commonjs/lib/tick.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/commonjs/lib/tick'>;
}
declare module 'semantic-ui-calendar-react/dist/commonjs/pickers/BasePicker.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/commonjs/pickers/BasePicker'>;
}
declare module 'semantic-ui-calendar-react/dist/commonjs/pickers/dayPicker/DatesRangePicker.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/commonjs/pickers/dayPicker/DatesRangePicker'>;
}
declare module 'semantic-ui-calendar-react/dist/commonjs/pickers/dayPicker/DayPicker.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/commonjs/pickers/dayPicker/DayPicker'>;
}
declare module 'semantic-ui-calendar-react/dist/commonjs/pickers/dayPicker/sharedFunctions.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/commonjs/pickers/dayPicker/sharedFunctions'>;
}
declare module 'semantic-ui-calendar-react/dist/commonjs/pickers/monthPicker/const.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/commonjs/pickers/monthPicker/const'>;
}
declare module 'semantic-ui-calendar-react/dist/commonjs/pickers/monthPicker/MonthPicker.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/commonjs/pickers/monthPicker/MonthPicker'>;
}
declare module 'semantic-ui-calendar-react/dist/commonjs/pickers/monthPicker/MonthRangePicker.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/commonjs/pickers/monthPicker/MonthRangePicker'>;
}
declare module 'semantic-ui-calendar-react/dist/commonjs/pickers/monthPicker/sharedFunctions.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/commonjs/pickers/monthPicker/sharedFunctions'>;
}
declare module 'semantic-ui-calendar-react/dist/commonjs/pickers/timePicker/HourPicker.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/commonjs/pickers/timePicker/HourPicker'>;
}
declare module 'semantic-ui-calendar-react/dist/commonjs/pickers/timePicker/MinutePicker.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/commonjs/pickers/timePicker/MinutePicker'>;
}
declare module 'semantic-ui-calendar-react/dist/commonjs/pickers/timePicker/sharedFunctions.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/commonjs/pickers/timePicker/sharedFunctions'>;
}
declare module 'semantic-ui-calendar-react/dist/commonjs/pickers/YearPicker.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/commonjs/pickers/YearPicker'>;
}
declare module 'semantic-ui-calendar-react/dist/commonjs/views/BaseCalendarView.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/commonjs/views/BaseCalendarView'>;
}
declare module 'semantic-ui-calendar-react/dist/commonjs/views/Calendar.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/commonjs/views/Calendar'>;
}
declare module 'semantic-ui-calendar-react/dist/commonjs/views/CalendarBody/Body.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/commonjs/views/CalendarBody/Body'>;
}
declare module 'semantic-ui-calendar-react/dist/commonjs/views/CalendarBody/Cell.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/commonjs/views/CalendarBody/Cell'>;
}
declare module 'semantic-ui-calendar-react/dist/commonjs/views/CalendarBody/index.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/commonjs/views/CalendarBody/index'>;
}
declare module 'semantic-ui-calendar-react/dist/commonjs/views/CalendarHeader/Header.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/commonjs/views/CalendarHeader/Header'>;
}
declare module 'semantic-ui-calendar-react/dist/commonjs/views/CalendarHeader/HeaderRange.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/commonjs/views/CalendarHeader/HeaderRange'>;
}
declare module 'semantic-ui-calendar-react/dist/commonjs/views/CalendarHeader/HeaderWeeks.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/commonjs/views/CalendarHeader/HeaderWeeks'>;
}
declare module 'semantic-ui-calendar-react/dist/commonjs/views/CalendarHeader/index.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/commonjs/views/CalendarHeader/index'>;
}
declare module 'semantic-ui-calendar-react/dist/commonjs/views/DatesRangeView.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/commonjs/views/DatesRangeView'>;
}
declare module 'semantic-ui-calendar-react/dist/commonjs/views/DayView.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/commonjs/views/DayView'>;
}
declare module 'semantic-ui-calendar-react/dist/commonjs/views/HourView.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/commonjs/views/HourView'>;
}
declare module 'semantic-ui-calendar-react/dist/commonjs/views/InputView.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/commonjs/views/InputView'>;
}
declare module 'semantic-ui-calendar-react/dist/commonjs/views/MinuteView.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/commonjs/views/MinuteView'>;
}
declare module 'semantic-ui-calendar-react/dist/commonjs/views/MonthRangeView.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/commonjs/views/MonthRangeView'>;
}
declare module 'semantic-ui-calendar-react/dist/commonjs/views/MonthView.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/commonjs/views/MonthView'>;
}
declare module 'semantic-ui-calendar-react/dist/commonjs/views/YearView.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/commonjs/views/YearView'>;
}
declare module 'semantic-ui-calendar-react/dist/es6/index.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/es6/index'>;
}
declare module 'semantic-ui-calendar-react/dist/es6/inputs/BaseInput.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/es6/inputs/BaseInput'>;
}
declare module 'semantic-ui-calendar-react/dist/es6/inputs/DateInput.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/es6/inputs/DateInput'>;
}
declare module 'semantic-ui-calendar-react/dist/es6/inputs/DatesRangeInput.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/es6/inputs/DatesRangeInput'>;
}
declare module 'semantic-ui-calendar-react/dist/es6/inputs/DateTimeInput.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/es6/inputs/DateTimeInput'>;
}
declare module 'semantic-ui-calendar-react/dist/es6/inputs/index.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/es6/inputs/index'>;
}
declare module 'semantic-ui-calendar-react/dist/es6/inputs/MonthInput.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/es6/inputs/MonthInput'>;
}
declare module 'semantic-ui-calendar-react/dist/es6/inputs/MonthRangeInput.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/es6/inputs/MonthRangeInput'>;
}
declare module 'semantic-ui-calendar-react/dist/es6/inputs/parse.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/es6/inputs/parse'>;
}
declare module 'semantic-ui-calendar-react/dist/es6/inputs/shared.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/es6/inputs/shared'>;
}
declare module 'semantic-ui-calendar-react/dist/es6/inputs/TimeInput.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/es6/inputs/TimeInput'>;
}
declare module 'semantic-ui-calendar-react/dist/es6/inputs/YearInput.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/es6/inputs/YearInput'>;
}
declare module 'semantic-ui-calendar-react/dist/es6/lib/checkIE.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/es6/lib/checkIE'>;
}
declare module 'semantic-ui-calendar-react/dist/es6/lib/checkMobile.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/es6/lib/checkMobile'>;
}
declare module 'semantic-ui-calendar-react/dist/es6/lib/CustomPropTypes.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/es6/lib/CustomPropTypes'>;
}
declare module 'semantic-ui-calendar-react/dist/es6/lib/findHTMLElement.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/es6/lib/findHTMLElement'>;
}
declare module 'semantic-ui-calendar-react/dist/es6/lib/index.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/es6/lib/index'>;
}
declare module 'semantic-ui-calendar-react/dist/es6/lib/tick.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/es6/lib/tick'>;
}
declare module 'semantic-ui-calendar-react/dist/es6/pickers/BasePicker.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/es6/pickers/BasePicker'>;
}
declare module 'semantic-ui-calendar-react/dist/es6/pickers/dayPicker/DatesRangePicker.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/es6/pickers/dayPicker/DatesRangePicker'>;
}
declare module 'semantic-ui-calendar-react/dist/es6/pickers/dayPicker/DayPicker.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/es6/pickers/dayPicker/DayPicker'>;
}
declare module 'semantic-ui-calendar-react/dist/es6/pickers/dayPicker/sharedFunctions.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/es6/pickers/dayPicker/sharedFunctions'>;
}
declare module 'semantic-ui-calendar-react/dist/es6/pickers/monthPicker/const.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/es6/pickers/monthPicker/const'>;
}
declare module 'semantic-ui-calendar-react/dist/es6/pickers/monthPicker/MonthPicker.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/es6/pickers/monthPicker/MonthPicker'>;
}
declare module 'semantic-ui-calendar-react/dist/es6/pickers/monthPicker/MonthRangePicker.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/es6/pickers/monthPicker/MonthRangePicker'>;
}
declare module 'semantic-ui-calendar-react/dist/es6/pickers/monthPicker/sharedFunctions.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/es6/pickers/monthPicker/sharedFunctions'>;
}
declare module 'semantic-ui-calendar-react/dist/es6/pickers/timePicker/HourPicker.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/es6/pickers/timePicker/HourPicker'>;
}
declare module 'semantic-ui-calendar-react/dist/es6/pickers/timePicker/MinutePicker.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/es6/pickers/timePicker/MinutePicker'>;
}
declare module 'semantic-ui-calendar-react/dist/es6/pickers/timePicker/sharedFunctions.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/es6/pickers/timePicker/sharedFunctions'>;
}
declare module 'semantic-ui-calendar-react/dist/es6/pickers/YearPicker.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/es6/pickers/YearPicker'>;
}
declare module 'semantic-ui-calendar-react/dist/es6/views/BaseCalendarView.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/es6/views/BaseCalendarView'>;
}
declare module 'semantic-ui-calendar-react/dist/es6/views/Calendar.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/es6/views/Calendar'>;
}
declare module 'semantic-ui-calendar-react/dist/es6/views/CalendarBody/Body.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/es6/views/CalendarBody/Body'>;
}
declare module 'semantic-ui-calendar-react/dist/es6/views/CalendarBody/Cell.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/es6/views/CalendarBody/Cell'>;
}
declare module 'semantic-ui-calendar-react/dist/es6/views/CalendarBody/index.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/es6/views/CalendarBody/index'>;
}
declare module 'semantic-ui-calendar-react/dist/es6/views/CalendarHeader/Header.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/es6/views/CalendarHeader/Header'>;
}
declare module 'semantic-ui-calendar-react/dist/es6/views/CalendarHeader/HeaderRange.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/es6/views/CalendarHeader/HeaderRange'>;
}
declare module 'semantic-ui-calendar-react/dist/es6/views/CalendarHeader/HeaderWeeks.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/es6/views/CalendarHeader/HeaderWeeks'>;
}
declare module 'semantic-ui-calendar-react/dist/es6/views/CalendarHeader/index.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/es6/views/CalendarHeader/index'>;
}
declare module 'semantic-ui-calendar-react/dist/es6/views/DatesRangeView.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/es6/views/DatesRangeView'>;
}
declare module 'semantic-ui-calendar-react/dist/es6/views/DayView.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/es6/views/DayView'>;
}
declare module 'semantic-ui-calendar-react/dist/es6/views/HourView.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/es6/views/HourView'>;
}
declare module 'semantic-ui-calendar-react/dist/es6/views/InputView.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/es6/views/InputView'>;
}
declare module 'semantic-ui-calendar-react/dist/es6/views/MinuteView.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/es6/views/MinuteView'>;
}
declare module 'semantic-ui-calendar-react/dist/es6/views/MonthRangeView.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/es6/views/MonthRangeView'>;
}
declare module 'semantic-ui-calendar-react/dist/es6/views/MonthView.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/es6/views/MonthView'>;
}
declare module 'semantic-ui-calendar-react/dist/es6/views/YearView.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/es6/views/YearView'>;
}
declare module 'semantic-ui-calendar-react/dist/umd/semantic-ui-calendar-react.js' {
  declare module.exports: $Exports<'semantic-ui-calendar-react/dist/umd/semantic-ui-calendar-react'>;
}
